/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ACollapse: typeof import('@arco-design/web-vue')['Collapse']
    ACollapseItem: typeof import('@arco-design/web-vue')['CollapseItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ARow: typeof import('@arco-design/web-vue')['Row']
    Desktop: typeof import('./src/components/base/Desktop.vue')['default']
    Drag: typeof import('./src/components/base/Drag.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Lore: typeof import('./src/components/Lore.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Setting.vue')['default']
    TakeNote: typeof import('./src/components/TakeNote.vue')['default']
    Taskbar: typeof import('./src/components/base/Taskbar.vue')['default']
    Theme: typeof import('./src/components/Theme.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
